Dataset:

MODIS + 96% clear

Augmentations:

1. RandomFlip()
2. RandomRotate()
3. JitterCrop()
  Inner 40x40 with up to 5 pixels of Jitter
4. Demean()

No Gaussian noise



Training Starts.
  0%|          | 0/50 [00:08<?, ?it/s]
Traceback (most recent call last):
  File "./ssl_modis_v4.py", line 437, in <module>
    main_train(args.opt_path, debug=args.debug)
  File "./ssl_modis_v4.py", line 78, in main_train
    loss, losses_step, losses_avg = train_model(
  File "/ulmo/ulmo/ssl/train_util.py", line 482, in train_model
    features = model(images)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/ulmo/ulmo/ssl/models/resnet_big.py", line 184, in forward
    feat = self.encoder(x)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 167, in forward
    replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 172, in replicate
    return replicate(module, device_ids, not torch.is_grad_enabled())
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/parallel/replicate.py", line 91, in replicate
    param_copies = _broadcast_coalesced_reshape(params, devices, detach)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/parallel/replicate.py", line 71, in _broadcast_coalesced_reshape
    tensor_copies = Broadcast.apply(devices, *tensors)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/parallel/_functions.py", line 23, in forward
    outputs = comm.broadcast_coalesced(inputs, ctx.target_gpus)
  File "/root/miniconda3/lib/python3.8/site-packages/torch/nn/parallel/comm.py", line 58, in broadcast_coalesced
    return torch._C._broadcast_coalesced(tensors, devices, buffer_size)
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.


In [1]: import torch
^[[A^[[A
In [2]: torch.__version__
Out[2]: '1.12.1+cu102'
